version: "3.2"
services:
  nginx:
    image: nginx-asset-uploader
    restart: always
    ports:
      - "80:8080"
    external_links:
      - uwsgi:uwsgi.container
  uwsgi:
    image: uwsgi-asset-uploader
    restart: always
